// 自动生成：lib/plugin-config-descriptors.ts → lib/config-schema.ts 迁移
// 字段类型映射：toggle→boolean / select→select / multiselect→string-list / text→string / number→number / list→string-list
// ponytail: enabled toggle 自动提升为顶级开关；group 启发式 (experimental/advanced → advanced)

import type { PluginSchema, FieldGroup } from "./config-schema";
export const SCHEMA_VERSION = "1.0.0" as const;

export const allSchemas: readonly PluginSchema[] = [
  {
    pluginId: "npm:context-mode",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--context-mode.fields.enabled",
    },
    fields: [
      {
        key: "compressionLevel",
        type: "select",
        default: "balanced",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--context-mode.fields.compressionLevel",
        options: [
          { value: "off", label: "关闭" },
          { value: "light", label: "轻度" },
          { value: "balanced", label: "均衡" },
          { value: "aggressive", label: "激进" },
        ],
      },
      {
        key: "sandboxExecution",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--context-mode.fields.sandboxExecution",
      },
      {
        key: "knowledgeBase",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--context-mode.fields.knowledgeBase",
      },
    ],
  },
  {
    pluginId: "npm:@hypabolic/pi-hypa",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--@hypabolic/pi-hypa.fields.enabled",
    },
    fields: [
      {
        key: "bridgeMode",
        type: "select",
        default: "on",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@hypabolic/pi-hypa.fields.bridgeMode",
        options: [
          { value: "on", label: "开启" },
          { value: "off", label: "关闭" },
        ],
      },
      {
        key: "recoverableEvidence",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@hypabolic/pi-hypa.fields.recoverableEvidence",
      },
    ],
  },
  {
    pluginId: "npm:pi-rtk",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--pi-rtk.fields.enabled",
    },
    fields: [
      {
        key: "filterLevel",
        type: "select",
        default: "balanced",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-rtk.fields.filterLevel",
        options: [
          { value: "conservative", label: "保守" },
          { value: "balanced", label: "均衡" },
          { value: "aggressive", label: "激进" },
        ],
      },
      {
        key: "maxOutputTokens",
        type: "number",
        default: 2000,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-rtk.fields.maxOutputTokens",
        min: 256,
        max: 32000,
        step: 256,
      },
    ],
  },
  {
    pluginId: "npm:cc-safety-net",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "blockDestructiveGit",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--cc-safety-net.fields.blockDestructiveGit",
      },
      {
        key: "blockDestructiveFs",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--cc-safety-net.fields.blockDestructiveFs",
      },
      {
        key: "requireConfirm",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--cc-safety-net.fields.requireConfirm",
      },
      {
        key: "allowlist",
        type: "string-list",
        default: [],
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--cc-safety-net.fields.allowlist",
        itemPlaceholder: "git reset --soft, git stash",
      },
    ],
  },
  {
    pluginId: "npm:pi-subagents",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "maxParallel",
        type: "number",
        default: 4,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-subagents.fields.maxParallel",
        min: 1,
        max: 32,
        step: 1,
      },
      {
        key: "enableTui",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-subagents.fields.enableTui",
      },
    ],
  },
  {
    pluginId: "npm:@juicesharp/rpiv-todo",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "showOverlay",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@juicesharp/rpiv-todo.fields.showOverlay",
      },
      {
        key: "surviveCompaction",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@juicesharp/rpiv-todo.fields.surviveCompaction",
      },
    ],
  },
  {
    pluginId: "npm:pi-lean-ctx",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--pi-lean-ctx.fields.enabled",
    },
    fields: [
      {
        key: "mode",
        type: "select",
        default: "lean",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-lean-ctx.fields.mode",
        options: [
          { value: "lean", label: "精简" },
          { value: "full", label: "完整" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:@ff-labs/pi-fff",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--@ff-labs/pi-fff.fields.enabled",
    },
    fields: [
      {
        key: "scope",
        type: "select",
        default: "repo",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@ff-labs/pi-fff.fields.scope",
        options: [
          { value: "repo", label: "整个仓库" },
          { value: "openFiles", label: "仅打开的文件" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:pi-readseek",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--pi-readseek.fields.enabled",
    },
    fields: [
      {
        key: "anchorPrecision",
        type: "select",
        default: "line",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-readseek.fields.anchorPrecision",
        options: [
          { value: "line", label: "行号" },
          { value: "hash", label: "内容哈希" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:pi-hashline-edit-pro",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--pi-hashline-edit-pro.fields.enabled",
    },
    fields: [
      {
        key: "createBackups",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-hashline-edit-pro.fields.createBackups",
      },
    ],
  },
  {
    pluginId: "npm:@braintrust/pi-extension",
    version: SCHEMA_VERSION,
    enabled: {
      key: "enabled",
      type: "boolean",
      default: true,
      group: "common" as FieldGroup,
      i18nKey: "settings.npm--@braintrust/pi-extension.fields.enabled",
    },
    fields: [
      {
        key: "exportFormat",
        type: "select",
        default: "jsonl",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@braintrust/pi-extension.fields.exportFormat",
        options: [
          { value: "jsonl", label: "JSONL" },
          { value: "csv", label: "CSV" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:pi-powerline-footer",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "showTokenCount",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-powerline-footer.fields.showTokenCount",
      },
      {
        key: "showCost",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-powerline-footer.fields.showCost",
      },
    ],
  },
  {
    pluginId: "npm:pi-search-hub",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "defaultBackend",
        type: "select",
        default: "firecrawl-keyless",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-search-hub.fields.defaultBackend",
        options: [
          { value: "firecrawl-keyless", label: "Firecrawl（免密）" },
          { value: "duckduckgo", label: "DuckDuckGo" },
          { value: "searxng", label: "SearXNG" },
          { value: "jina", label: "Jina Reader" },
          { value: "tavily", label: "Tavily（需 key）" },
          { value: "brave", label: "Brave（需 key）" },
          { value: "exa", label: "Exa（需 key）" },
          { value: "perplexity", label: "Perplexity Sonar（需 key）" },
        ],
      },
      {
        key: "searxngUrl",
        type: "string",
        default: "",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-search-hub.fields.searxngUrl",
        placeholder: "https://searxng.example.com",
      },
      {
        key: "enableExtraction",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-search-hub.fields.enableExtraction",
      },
      {
        key: "maxResults",
        type: "number",
        default: 5,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-search-hub.fields.maxResults",
        min: 1,
        max: 50,
        step: 1,
      },
    ],
  },
  {
    pluginId: "npm:pi-mcp-adapter",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "autoConnect",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-mcp-adapter.fields.autoConnect",
      },
      {
        key: "servers",
        type: "string-list",
        default: [],
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-mcp-adapter.fields.servers",
        itemPlaceholder: "npx -y @modelcontextprotocol/server-filesystem /path",
      },
    ],
  },
  {
    pluginId: "npm:@juicesharp/rpiv-ask-user-question",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "maxOptions",
        type: "number",
        default: 4,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@juicesharp/rpiv-ask-user-question.fields.maxOptions",
        min: 2,
        max: 8,
        step: 1,
      },
      {
        key: "requireTyped",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@juicesharp/rpiv-ask-user-question.fields.requireTyped",
      },
    ],
  },
  {
    pluginId: "npm:pi-lens",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "enableLsp",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-lens.fields.enableLsp",
      },
      {
        key: "enableLinters",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-lens.fields.enableLinters",
      },
      {
        key: "enableFormatters",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-lens.fields.enableFormatters",
      },
      {
        key: "failOnError",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-lens.fields.failOnError",
      },
    ],
  },
  {
    pluginId: "npm:pi-simplify",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "autoReview",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-simplify.fields.autoReview",
      },
      {
        key: "scope",
        type: "select",
        default: "changed",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-simplify.fields.scope",
        options: [
          { value: "changed", label: "变更文件" },
          { value: "all", label: "整个仓库" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:pi-shazam",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "enableStructural",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-shazam.fields.enableStructural",
      },
      {
        key: "enableMcp",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-shazam.fields.enableMcp",
      },
    ],
  },
  {
    pluginId: "npm:pi-hermes-memory",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "policyMode",
        type: "select",
        default: "token-aware",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-hermes-memory.fields.policyMode",
        options: [
          { value: "token-aware", label: "Token 感知（默认）" },
          { value: "full", label: "完整" },
        ],
      },
      {
        key: "enableSecretScan",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-hermes-memory.fields.enableSecretScan",
      },
      {
        key: "autoConsolidate",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-hermes-memory.fields.autoConsolidate",
      },
    ],
  },
  {
    pluginId: "npm:@juicesharp/rpiv-advisor",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "autoRequest",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@juicesharp/rpiv-advisor.fields.autoRequest",
      },
      {
        key: "reviewerModel",
        type: "string",
        default: "",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@juicesharp/rpiv-advisor.fields.reviewerModel",
        placeholder: "例如 gpt-4o",
      },
    ],
  },
  {
    pluginId: "npm:gentle-pi",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "enforcement",
        type: "select",
        default: "strict",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--gentle-pi.fields.enforcement",
        options: [
          { value: "strict", label: "严格" },
          { value: "loose", label: "宽松" },
        ],
      },
      {
        key: "requireTddEvidence",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--gentle-pi.fields.requireTddEvidence",
      },
    ],
  },
  {
    pluginId: "npm:@plannotator/pi-extension",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "enableAnnotations",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@plannotator/pi-extension.fields.enableAnnotations",
      },
      {
        key: "reviewMode",
        type: "select",
        default: "interactive",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@plannotator/pi-extension.fields.reviewMode",
        options: [
          { value: "interactive", label: "交互式" },
          { value: "batch", label: "批量" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:pi-landstrip",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "sandboxMode",
        type: "select",
        default: "prompt",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-landstrip.fields.sandboxMode",
        options: [
          { value: "prompt", label: "逐操作询问" },
          { value: "auto", label: "自动拒绝未知操作" },
        ],
      },
      {
        key: "requireConfirm",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-landstrip.fields.requireConfirm",
      },
    ],
  },
  {
    pluginId: "npm:pi-agent-browser-native",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "headless",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-agent-browser-native.fields.headless",
      },
      {
        key: "viewport",
        type: "select",
        default: "desktop",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-agent-browser-native.fields.viewport",
        options: [
          { value: "desktop", label: "桌面（1280x800）" },
          { value: "mobile", label: "移动端（390x844）" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:superpowers-zh",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "enableSkills",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--superpowers-zh.fields.enableSkills",
      },
    ],
  },
  {
    pluginId: "npm:@raindrop-ai/pi-agent",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "traceLevel",
        type: "select",
        default: "call",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@raindrop-ai/pi-agent.fields.traceLevel",
        options: [
          { value: "session", label: "会话级" },
          { value: "turn", label: "轮次级" },
          { value: "call", label: "LLM 调用 + 工具" },
        ],
      },
      {
        key: "exportTraces",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@raindrop-ai/pi-agent.fields.exportTraces",
      },
    ],
  },
  {
    pluginId: "npm:@gotgenes/pi-permission-system",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "yoloMode",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@gotgenes/pi-permission-system.fields.yoloMode",
      },
      {
        key: "permissionReviewLog",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@gotgenes/pi-permission-system.fields.permissionReviewLog",
      },
      {
        key: "debugLog",
        type: "boolean",
        default: false,
        group: "advanced" as FieldGroup,
        i18nKey: "settings.npm--@gotgenes/pi-permission-system.fields.debugLog",
      },
      {
        key: "toolInputPreviewMaxLength",
        type: "number",
        default: 200,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@gotgenes/pi-permission-system.fields.toolInputPreviewMaxLength",
        min: 0,
        max: 2000,
        step: 10,
      },
      {
        key: "toolTextSummaryMaxLength",
        type: "number",
        default: 80,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@gotgenes/pi-permission-system.fields.toolTextSummaryMaxLength",
        min: 0,
        max: 500,
        step: 10,
      },
    ],
  },
  {
    pluginId: "npm:latchkey",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "credentialSource",
        type: "string",
        default: "",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--latchkey.fields.credentialSource",
        placeholder: "env:API_KEY 或 ~/.latchkey.json",
      },
      {
        key: "injectMode",
        type: "select",
        default: "header",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--latchkey.fields.injectMode",
        options: [
          { value: "header", label: "请求头" },
          { value: "query", label: "查询参数" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:@ayulab/pi-rewind",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "maxCheckpoints",
        type: "number",
        default: 20,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@ayulab/pi-rewind.fields.maxCheckpoints",
        min: 1,
        max: 200,
        step: 1,
      },
      {
        key: "autoCheckpoint",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@ayulab/pi-rewind.fields.autoCheckpoint",
      },
    ],
  },
  {
    pluginId: "npm:@dietrichgebert/ponytail",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "disciplineLevel",
        type: "select",
        default: "lazy",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@dietrichgebert/ponytail.fields.disciplineLevel",
        options: [
          { value: "lazy", label: "慵懒（优先复用）" },
          { value: "balanced", label: "均衡" },
        ],
      },
      {
        key: "warnOnNewCode",
        type: "boolean",
        default: false,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@dietrichgebert/ponytail.fields.warnOnNewCode",
      },
    ],
  },
  {
    pluginId: "npm:pi-caveman",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "mode",
        type: "select",
        default: "lite",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-caveman.fields.mode",
        options: [
          { value: "lite", label: "轻度" },
          { value: "full", label: "完整" },
          { value: "ultra", label: "极致" },
          { value: "wenyan", label: "文言文" },
          { value: "micro", label: "微型" },
        ],
      },
    ],
  },
  {
    pluginId: "npm:@heyhuynhgiabuu/pi-pretty",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "background.tool",
        type: "string",
        default: "",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@heyhuynhgiabuu/pi-pretty.fields.background.tool",
        placeholder: "#1e1e2e",
      },
      {
        key: "background.error",
        type: "string",
        default: "",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--@heyhuynhgiabuu/pi-pretty.fields.background.error",
        placeholder: "#3b1e1e",
      },
    ],
  },
  {
    pluginId: "npm:pi-web-access",
    version: SCHEMA_VERSION,
    fields: [
      {
        key: "provider",
        type: "select",
        default: "auto",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-web-access.fields.provider",
        options: [
          { value: "auto", label: "自动（auto）" },
          { value: "openai", label: "OpenAI" },
          { value: "brave", label: "Brave" },
          { value: "parallel", label: "Parallel" },
          { value: "tavily", label: "Tavily" },
          { value: "exa", label: "Exa" },
          { value: "perplexity", label: "Perplexity" },
          { value: "gemini", label: "Gemini" },
        ],
      },
      {
        key: "curatorTimeoutSeconds",
        type: "number",
        default: 20,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-web-access.fields.curatorTimeoutSeconds",
        min: 1,
        max: 600,
        step: 5,
      },
      {
        key: "workflow",
        type: "select",
        default: "summary-review",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-web-access.fields.workflow",
        options: [
          { value: "summary-review", label: "摘要 + 审查" },
          { value: "auto-summary", label: "自动摘要" },
          { value: "none", label: "无" },
        ],
      },
      {
        key: "summaryModel",
        type: "string",
        default: "",
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-web-access.fields.summaryModel",
        placeholder: "例如 gpt-4o-mini",
      },
      {
        key: "webSearch.enabled",
        type: "boolean",
        default: true,
        group: "common" as FieldGroup,
        i18nKey: "settings.npm--pi-web-access.fields.webSearch.enabled",
      },
    ],
  },
] as const;
