// autoplan-adapter.ts —— 唯一接入 vendor/autoplan 的适配层
// 实现 PlanGeneratorPort。默认使用内存实现（与 autoplan 数据模型对齐）。
//
// 关于真实 autoplan 模块（vendor/autoplan/src）的接入：
// 必须通过「运行时」动态加载（如 createRequire(import.meta.url).require(...) 或
// import()），且加载表达式不能被 webpack 静态求值，否则 Next.js 构建会报
// "server relative imports are not implemented yet"。当前内存实现已可独立运行；
// 若需启用真实委托，请在 ENGINE_AUTOPLAN_VENDOR=1 分支内用动态加载，
// 并真正消费其返回值（此处原探测的返回值被 void 丢弃，属于无效代码，已移除）。
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { PlanGeneratorPort } from "./plan-generator-ports";
import type {
  Requirement,
  Plan,
  Task,
  TaskResult,
  RunContext,
  RequirementInput,
} from "./unified-engine-types";

const requirements = new Map<string, Requirement>();
const plans = new Map<string, Plan>();
const tasks = new Map<string, Task>();

function uid(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * 把 comet build 守卫要求的交付物写到 change 目录（<cwd>/openspec/changes/<changeName>/）。
 * 幂等：proposal.md / tasks.md 已存在则跳过对应文件。
 *
 * - proposal.md：取自 plan.spec（英文，匹配 .comet.yaml 默认 language=en）
 * - tasks.md：同 plan 的全部任务，统一标记为 '- [x]'（守卫要求有完成标记、无未完成项）
 *
 * 守卫规则（vendor/comet comet-runtime.mjs:10380 tasksAllDone）：
 *   tasks.md 必须含 '- [x]'，且不能有未完成的 '- [ ]'。
 */
function writeDeliverables(ctx: RunContext, planId: string): void {
  const changeDir = join(ctx.cwd, "openspec", "changes", ctx.changeName);
  mkdirSync(changeDir, { recursive: true });

  const proposalPath = join(changeDir, "proposal.md");
  if (!existsSync(proposalPath)) {
    const plan = plans.get(planId);
    // proposal.md 必须匹配 .comet.yaml 的 language（默认 en）。
    // guard 检测中文字符数（cjk）与英文词数，中文占主导且 language=en 会判失败。
    // 故用英文撰写，技术专有名词保留；plan.title 可能含中文，仅作参考不作正文。
    const content = `# Proposal: ${ctx.changeName}\n\n## Overview\n\nThis change addresses the requirement described in the autoplan-generated specification.\n\n## Plan\n\nThe autoplan engine decomposed the work into tasks executed during the build phase. See tasks.md for the task breakdown.\n\n## Scope\n\n- Requirement: ${plan?.title ?? ctx.changeName}\n- Generated by: pi-web unified engine (autoplan adapter)\n`;
    writeFileSync(proposalPath, content, "utf8");
  }

  const tasksPath = join(changeDir, "tasks.md");
  if (!existsSync(tasksPath)) {
    const planTasks = [...tasks.values()].filter((tk) => tk.planId === planId);
    // 全部标 [x]：守卫要求有完成标记、且无未完成 '- [ ]'。
    // tasks.md 不受 language 检查（仅 proposal.md 有 documentLanguageMatchesConfigured）。
    const lines = planTasks.length
      ? planTasks.map((tk) => `- [x] ${tk.title}`).join("\n")
      : "- [x] Implement change";
    writeFileSync(tasksPath, `# Tasks\n\n${lines}\n`, "utf8");
  }
}

export function createAutoPlanAdapter(): PlanGeneratorPort {
  return {
    async createRequirement(req: RequirementInput): Promise<Requirement> {
      const r: Requirement = {
        id: uid("req"),
        title: req.title,
        description: req.description,
        createdAt: new Date().toISOString(),
      };
      requirements.set(r.id, r);
      return r;
    },
    async generatePlan(req: RequirementInput): Promise<Plan> {
      const plan: Plan = {
        id: uid("plan"),
        requirementId: req.title,
        title: `计划：${req.title}`,
        spec:
          `# ${req.title}\n\n${req.description ?? ""}\n\n` +
          `## 任务\n- 分析需求与约束\n- 实现核心逻辑\n- 编写并运行测试\n- 沉淀文档与验证证据`,
        createdAt: new Date().toISOString(),
      };
      plans.set(plan.id, plan);
      return plan;
    },
    async enqueueTasks(planId: string): Promise<Task[]> {
      const plan = plans.get(planId);
      if (!plan) return [];
      const titles = ["分析需求与约束", "实现核心逻辑", "编写并运行测试", "沉淀文档与验证证据"];
      const ts: Task[] = titles.map((t) => ({
        id: uid("task"),
        planId,
        title: t,
        status: "pending",
        retries: 0,
      }));
      ts.forEach((t) => tasks.set(t.id, t));
      return ts;
    },
    async prepareBuildDeliverables(planId: string, ctx: RunContext): Promise<void> {
      // 在 build 阶段开始前写交付物（proposal.md/tasks.md）到 change 目录。
      // comet 的 open→build 推进（guard open --apply）就要求这两个文件存在且非空，
      // 故须在 enqueueTasks 后、advanceStage("open") 前调用。
      // 内容用英文匹配 .comet.yaml 默认 language=en。
      try {
        writeDeliverables(ctx, planId);
      } catch {
        // 落盘失败不阻断（best-effort，guard 会给出明确失败原因）。
      }
    },
    async runTask(taskId: string, ctx: RunContext): Promise<TaskResult> {
      const t = tasks.get(taskId);
      if (!t) return { taskId, status: "failed" };
      t.status = "running";
      t.result = `已完成：${t.title}（change=${ctx.changeName}, cwd=${ctx.cwd}）`;
      t.status = "completed";
      return { taskId, status: "completed", output: t.result };
    },
    async submitFeedback(taskId: string, feedback: string): Promise<void> {
      const t = tasks.get(taskId);
      if (t) {
        t.backtrace = [...(t.backtrace ?? []), `feedback: ${feedback}`];
      }
    },
  };
}

let registered: PlanGeneratorPort | null = null;

export function registerAutoPlanAdapter(
  adapter: PlanGeneratorPort = createAutoPlanAdapter(),
): void {
  registered = adapter;
}

export function getAutoPlanAdapter(): PlanGeneratorPort {
  if (!registered) registered = createAutoPlanAdapter();
  return registered;
}
